### ISSUE TITLE
Align headers

### ISSUE THREAD

**Issue by mitchellsimoens** [cli-table/cli-table3#100]
Thank you for keeping this project active.

It would be great if headers could use same defaults that Cell can take. My current want is to center align a header when a cell text is longer than the heading:

![Screen Shot 2019-04-15 at 11 59 02 AM](https://user-images.githubusercontent.com/325473/56147243-e1771180-5f75-11e9-92f5-5be4e126ab64.png)

Example:

```typescript
const foo = new Table({
  head: ['foo'],
}) as HorizontalTable;

foo.push(['something longer than the head']);

console.log(foo.toString());
```

I'd like something along these lines:

```typescript
const foo = new Table({
  head: [{ content: 'foo', hAlign: 'center' }],
}) as HorizontalTable;

foo.push(['something longer than the head']);

console.log(foo.toString());
```

which would get me:

![Screen Shot 2019-04-15 at 12 01 58 PM](https://user-images.githubusercontent.com/325473/56147457-4d597a00-5f76-11e9-9564-6c5159280799.png)

**Comment by speedytwenty** [comment]
I'm not sure if this perhaps wasn't functioning at the time this issue was posted. But when I test the code from your second example, I get what you are wanting/expecting. Eg.

![image](https://user-images.githubusercontent.com/260874/160292777-e087e574-4723-4ed5-88a1-7313cbc239e8.png)

Not sure if this was resolved in the meantime, but closing for now. If there is still an issue, please reopen.
